ALTER TABLE STUDENT ADD (CONSTRAINT age_constraint CHECK (age > 16));
ALTER TABLE STUDENT ALTER COLUMN NAME SET NOT NULL;
ALTER TABLE FACULTY
ADD CONSTRAINT faculty_unique UNIQUE (color);
ALTER TABLE STUDENT ALTER COLUMN NAME SET DEFAULT 20;